feat(LayerEntry): Convert from MUI to bootstrap
InsightSoftwareConsortium/itk-viewer-bootstrap-ui pull request #17
Opened 2022-06-07 18:52 UTC by labdala

In this version we have place holders for the Tooltips.
We also change the style of the bar to look more closely to the original App. 

**To-do**: optimize re-renders

2022-06-10 19:24 UTC, labdala commented
There is something up with the layers that make them re-render more often than they should. That is aside from the `applyContrastSensitiveStyleToElement` to create the dark mode.

2022-06-13 12:39 UTC, PaulHax commented
Here is another test case that loads a "label image" layer.  Useful because the extra layer changes the layout.  It uses test data from the main repo and loads the data via a local HTTP server.  We can go over how to run this later:

```
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/itk-vtk-viewer@11.12.4/dist/itkVtkViewer.js"></script>
    <script>
      const container = document.querySelector('.content')
      const ipfsImage = new URL("http://localhost:8082/test-data/HeadMRVolume.nrrd")
      const label = new URL("http://localhost:8082/test-data/HeadMRVolumeLabels.nrrd")
      const uiMachineOptions = { href: new URL("/src/materialUIMachineOptions.js", document.location.origin).href }
      itkVtkViewer.createViewer(container,
        {
        image: ipfsImage,
        labelImage: label,
        rotate: false,
        config: { uiMachineOptions },
        })
    </script>
```

2022-06-14 21:37 UTC, labdala commented
Opened issue #28 to address problem pointed out in commits [47a78b6](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/17/commits/47a78b675766835bf9e4beb9b0f6bf94dceb44f1) and [4cab70d](https://github.com/InsightSoftwareConsortium/itk-viewer-bootstrap-ui/pull/17/commits/4cab70da41d0ebb15495b77a4a43bc686605a3e3): 

the TransferFunctionWidget should disappear when using only labelImage.

2022-06-15 14:02 UTC, PaulHax requested changes
Can we have Image and LabelImage on the same row to save some vertical pixels?  Main repo app look:
![image](https://user-images.githubusercontent.com/16823231/173845655-742ce074-8801-417e-86e6-d414c837174b.png)

The picture and label icons on the right side seem clickable with that focus issue we had on the "sample distance" icons.

2022-06-15 19:43 UTC, labdala commented on src/Images/ImagesInterface.jsx
> +  console.log(layersContext)
The disadvantage of saving vertical space is that, for files that have long names, the visibility button does not fit the screen:
![image](https://user-images.githubusercontent.com/60415505/173910959-fd37c6cb-e716-4770-afac-467e56f6de92.png)
I am not sure if an user would load more than 2 files, but I suppose they would run into the same issue(?)

2022-06-16 12:13 UTC, PaulHax commented on src/Images/ImagesInterface.jsx
> +  console.log(layersContext)
Good point.  Rows per image it is then.

2022-06-16 14:17 UTC, labdala commented on src/Images/ImagesInterface.jsx
> +  console.log(layersContext)
yay! Do you think this PR is ready to merge?

2022-06-16 14:25 UTC, PaulHax approved these changes
Looks good!

2022-06-16 17:57 UTC, merged