feat(bootstrap): Rewrite GradientOpacitySlider and update style
InsightSoftwareConsortium/itk-viewer-bootstrap-ui pull request #8
Opened 2022-06-02 19:01 UTC by labdala

-  Re-write GradientOpacitySlider using bootstrap;
 - Change `style.css` selector's properties to have wider sliders, and to enable vertical slider

2022-06-02 21:05 UTC, PaulHax approved these changes

2022-06-02 21:05 UTC, PaulHax commented on src/Images/GradientOpacitySlider.jsx
> +  const state = useSelector(service, (state) => state)
Select state component needs.

2022-06-06 16:01 UTC, labdala commented
This pull request has already been approved. @PaulHax, could you please confirm whether you think this branch is ready to be merged since I made some changes?

2022-06-06 16:20 UTC, PaulHax requested changes
When I drag the sliders, the ticks don't move.  Hmmm.  Something is broken in the state update flow.  Check that the component re-renders and the state value changes.

The `IMAGE_GRADIENT_OPACITY_CHANGED` slider does not seem to update the rendering.

2022-06-06 19:40 UTC, labdala commented on src/Images/GradientOpacitySlider.jsx
> +          <Form.Group>
Yes and right. The first problem is related to the use of React.memo again. I just deleted it.

2022-06-07 13:18 UTC, PaulHax approved these changes
Lets do it!

2022-06-07 13:44 UTC, labdala commented
Thank you so much for your suggestions @PaulHax !

2022-06-07 13:49 UTC, merged